"""
Enhanced scenario data with difficulty levels, sentiment, and metadata.
Each scenario includes:
  - email: Customer message
  - label: True category (refund/complaint/query)
  - difficulty: easy/medium/hard
  - sentiment: negative/neutral/positive
  - urgency: low/medium/high
  - complexity: 1-5 scale
  - requires_escalation: bool
  - min_reply_length: Minimum response length expectation
"""

SCENARIOS = [
    # Easy scenarios - clear intent, straightforward handling
    {
        "email": "I want a refund for my order",
        "label": "refund",
        "difficulty": "easy",
        "sentiment": "neutral",
        "urgency": "low",
        "complexity": 1,
        "requires_escalation": False,
        "min_reply_length": 30,
    },
    {
        "email": "Can you tell me delivery status?",
        "label": "query",
        "difficulty": "easy",
        "sentiment": "neutral",
        "urgency": "low",
        "complexity": 1,
        "requires_escalation": False,
        "min_reply_length": 20,
    },
    {
        "email": "Where is my package?",
        "label": "query",
        "difficulty": "easy",
        "sentiment": "neutral",
        "urgency": "low",
        "complexity": 1,
        "requires_escalation": False,
        "min_reply_length": 20,
    },
    {
        "email": "How long does delivery take?",
        "label": "query",
        "difficulty": "easy",
        "sentiment": "neutral",
        "urgency": "low",
        "complexity": 1,
        "requires_escalation": False,
        "min_reply_length": 25,
    },
    # Medium scenarios - mixed signals, requires judgment
    {
        "email": "Your service is terrible, I'm very unhappy",
        "label": "complaint",
        "difficulty": "medium",
        "sentiment": "negative",
        "urgency": "medium",
        "complexity": 2,
        "requires_escalation": True,
        "min_reply_length": 40,
    },
    {
        "email": "I need to cancel and get refund urgently",
        "label": "refund",
        "difficulty": "medium",
        "sentiment": "negative",
        "urgency": "high",
        "complexity": 2,
        "requires_escalation": False,
        "min_reply_length": 50,
    },
    {
        "email": "Product arrived damaged, I need help",
        "label": "complaint",
        "difficulty": "medium",
        "sentiment": "negative",
        "urgency": "medium",
        "complexity": 2,
        "requires_escalation": True,
        "min_reply_length": 45,
    },
    {
        "email": "Refund my money immediately",
        "label": "refund",
        "difficulty": "medium",
        "sentiment": "negative",
        "urgency": "high",
        "complexity": 2,
        "requires_escalation": False,
        "min_reply_length": 40,
    },
    {
        "email": "This is unacceptable service",
        "label": "complaint",
        "difficulty": "medium",
        "sentiment": "negative",
        "urgency": "medium",
        "complexity": 2,
        "requires_escalation": True,
        "min_reply_length": 50,
    },
    {
        "email": "I was charged twice!",
        "label": "complaint",
        "difficulty": "medium",
        "sentiment": "negative",
        "urgency": "high",
        "complexity": 2,
        "requires_escalation": True,
        "min_reply_length": 45,
    },
    # Hard scenarios - ambiguous, edge cases, multi-intent
    {
        "email": "I need to cancel and get refund urgently. Your support team is not responding!",
        "label": "complaint",
        "difficulty": "hard",
        "sentiment": "negative",
        "urgency": "high",
        "complexity": 4,
        "requires_escalation": True,
        "min_reply_length": 60,
    },
    {
        "email": "Product quality is poor but I'm willing to try again if you help",
        "label": "complaint",
        "difficulty": "hard",
        "sentiment": "mixed",
        "urgency": "medium",
        "complexity": 4,
        "requires_escalation": True,
        "min_reply_length": 70,
    },
    {
        "email": "Do you offer express shipping? I had a bad experience last time",
        "label": "query",
        "difficulty": "hard",
        "sentiment": "mixed",
        "urgency": "medium",
        "complexity": 3,
        "requires_escalation": False,
        "min_reply_length": 50, 
    },
    {
        "email": "Extremely disappointed. Refund not received. What's happening?",
        "label": "complaint",
        "difficulty": "hard",
        "sentiment": "negative",
        "urgency": "high",
        "complexity": 4,
        "requires_escalation": True,
        "min_reply_length": 60,
    },
    # Additional balanced set
    {
        "email": "Do you offer express shipping?",
        "label": "query",
        "difficulty": "easy",
        "sentiment": "neutral",
        "urgency": "low",
        "complexity": 1,
        "requires_escalation": False,
        "min_reply_length": 25,
    },
    {
        "email": "What are your working hours?",
        "label": "query",
        "difficulty": "easy",
        "sentiment": "neutral",
        "urgency": "low",
        "complexity": 1,
        "requires_escalation": False,
        "min_reply_length": 20,
    },
    {
        "email": "Can I change my delivery address?",
        "label": "query",
        "difficulty": "easy",
        "sentiment": "neutral",
        "urgency": "low",
        "complexity": 1,
        "requires_escalation": False,
        "min_reply_length": 25,
    },
    {
        "email": "Your support team is not responding",
        "label": "complaint",
        "difficulty": "medium",
        "sentiment": "negative",
        "urgency": "medium",
        "complexity": 2,
        "requires_escalation": True,
        "min_reply_length": 45,
    },
]
