apiVersion: v1
kind: Service
metadata:
  name: meta-env
  namespace: meta-environment
  labels:
    app.kubernetes.io/name: meta-environment
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: meta-environment
    app.kubernetes.io/component: api
